name: fexm
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  firebase_storage: ^3.0.6
  path_provider: ^1.4.0
  google_sign_in: ^4.0.7
  image_picker: ^0.6.1+4
  image_cropper: ^1.1.0
  liquid_progress_indicator: ^0.3.2
  curved_navigation_bar: ^0.3.1
  mailer: ^3.0.4
  worm_indicator: 0.1.1
  flutter_colorpicker: ^0.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: ave
      fonts:
       - asset: assets/fonts/AvenirLTStd-Black.otf
         weight: 700
       - asset: assets/fonts/AvenirLTStd-Heavy.otf
         weight: 600
       - asset: assets/fonts/AvenirLTStd-Medium.otf
         weight: 500
       - asset: assets/fonts/AvenirLTStd-Roman.otf
         weight: 400
       - asset: assets/fonts/AvenirLTStd-Book.otf
         weight: 300
       - asset: assets/fonts/AvenirLTStd-Light.otf
         weight: 200
    - family: lato
      fonts:
       - asset: assets/fonts/lato_black.ttf
         weight: 700
       - asset: assets/fonts/lato_bold.ttf
         weight: 600
       - asset: assets/fonts/lato_regu.ttf
         weight: 500
       - asset: assets/fonts/lato_light.ttf
         weight: 400
       - asset: assets/fonts/lato_hair.ttf
         weight: 300
    - family: prox
      fonts:
       - asset: assets/fonts/p_black.otf
         weight: 700
       - asset: assets/fonts/p_extra_bold.otf
         weight: 600
       - asset: assets/fonts/p_bold.otf
         weight: 500
       - asset: assets/fonts/ProximaNova-Regular.otf
         weight: 400
       - asset: assets/fonts/p_thin.otf
         weight: 300
    - family: teko
      fonts:
       - asset: assets/fonts/Teko-Bold.ttf
         weight: 700
       - asset: assets/fonts/Teko-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Teko-Medium.ttf
         weight: 500
       - asset: assets/fonts/Teko-Regular.ttf
         weight: 400
       - asset: assets/fonts/Teko-Light.ttf
         weight: 300
    - family: merri
      fonts:
       - asset: assets/fonts/m_black.ttf
         weight: 700
       - asset: assets/fonts/m_bold.ttf
         weight: 600
       - asset: assets/fonts/m_light.ttf
         weight: 500
       - asset: assets/fonts/m_regular.ttf
         weight: 400
    - family: chivo
      fonts:
       - asset: assets/fonts/c_black.ttf
         weight: 700
       - asset: assets/fonts/c_bold.ttf
         weight: 600
       - asset: assets/fonts/c_reg.ttf
         weight: 500
       - asset: assets/fonts/c_light.ttf
         weight: 400
    - family: rob
      fonts:
       - asset: assets/fonts/RobotoSlab-Bold.ttf
         weight: 700
       - asset: assets/fonts/RobotoSlab-Regular.ttf
         weight: 600
       - asset: assets/fonts/RobotoSlab-Light.ttf
         weight: 500
       - asset: assets/fonts/RobotoSlab-Thin.ttf
         weight: 400
    - family: cap
      fonts:
        - asset: assets/fonts/Capture it.ttf
    - family: his
      fonts:
        - asset: assets/fonts/historia.ttf
    - family: heinz
      fonts:
        - asset: assets/fonts/heinz.ttf
    - family: qua
      fonts:
        - asset: assets/fonts/Quantify.ttf
    - family: cool
      fonts:
        - asset: assets/fonts/coolvetica rg.ttf
    - family: muli
      fonts:
        - asset: assets/fonts/Muli-Black.ttf
          weight: 700
        - asset: assets/fonts/Muli-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 500
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 300
        - asset: assets/fonts/Muli-Light.ttf
          weight: 200
        - asset: assets/fonts/Muli-ExtraLight.ttf
          weight: 100
  assets:
    - assets/girisback.png
    - assets/matbaacim_t.png
    - assets/rek1.jpg
    - assets/rek2.jpg
    - assets/rek3.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
